version: "3"

services:
  db:
    image: mariadb:10.3
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:24-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - OVERWRITEPROTOCOL=http
    env_file:
      - db.env
      - s3.env
    depends_on:
      - db

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:z,ro
    environment:
      - VIRTUAL_HOST=localhost
    ports:
      - 8089:80
    depends_on:
      - db
  minio:
    image: docker.io/bitnami/minio:2022
    volumes:
      - "minio:/data"
    environment:
      - MINIO_ROOT_USER=nextcloud
      - MINIO_ROOT_PASSWORD=nextcloud
      - MINIO_DEFAULT_BUCKETS=nextcloud
    ports:
      - 9001:9001

volumes:
  db:
  nextcloud:
  minio:
